# Generated by Django 4.1.5 on 2023-02-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_client_qarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='qarz',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
